#!/usr/bin/env bash

ARG_HELP=
ARG_MACHINE_NAME="${DOCKER_MACHINE_NAME}"

while [[ $# > 0 ]] ; do
  case $1 in
    -h|--help)
      ARG_HELP=YES
    ;;
    *)
      ARG_MACHINE_NAME="$2"
      shift
    ;;
  esac
  shift
done

if [[ -n "${ARG_HELP}" ]]; then
  echo "Set up environment variables for connecting to Docker"
  echo "Usage:  . $0 [Docker Machine Name]"
  exit 0
fi

eval "$(docker-machine env ${ARG_MACHINE_NAME})"
