#!/usr/bin/env bash

ARG_SERVICE="app"

while [[ $# > 0 ]]
do
  key="$1"
  case $key in
    -h|--help)
      ARG_HELP=YES
    ;;
    -s|--service)
      ARG_SERVICE="$2"
      shift
    ;;
  esac
  shift
done

if [[ -n "$ARG_HELP" ]]; then
  echo "Start an interactive console in the container"
  echo "Automatically starts the container if not running"
  echo "  -s, --service   Specify the container"
  exit 0
fi

.docker/start -s $ARG_SERVICE -b -d 2>&1 | grep -v "up-to-date"
docker-compose exec $ARG_SERVICE /bin/bash
