#!/usr/bin/env bash

ARG_CONTAINER="app"

ARG_ARGUMENTS=
while [[ $# > 0 ]]
do
  key="$1"
  case $key in
    -h|--help)
      ARG_HELP=YES
    ;;
    -c|--container)
      ARG_CONTAINER="$2"
      shift
    ;;
    *)
      ARG_ARGUMENTS="$ARG_ARGUMENTS $key"
    ;;
  esac
  shift
done

if [[ -n "$ARG_HELP" ]]; then
  echo "Start an interactive console in the container"
  echo "Automatically starts the container if not running"
  echo "Usage:  $0 [-c CONTAINER] [bash ARGUMENTS]"
  exit 0
fi

.docker/start -s $ARG_CONTAINER -b -d 2>&1 | grep -v "up-to-date"
docker-compose exec $ARG_CONTAINER /bin/bash $ARG_ARGUMENTS
