#!/usr/bin/env bash

ARG_SERVICE="app"

while [[ $# > 0 ]]
do
  key="$1"
  case $key in
    -h|--help)
      ARG_HELP=YES
    ;;
    -s|--service)
      ARG_SERVICE="$2"
      shift
    ;;
    -b|--bash)
      ARG_STARTBASH=YES
    ;;
    -d|--daemon)
      ARG_DAEMON="-d"
    ;;
  esac
  shift
done

if [[ -n "$ARG_HELP" ]]; then
  echo "Start a Docker container and its depencencies"
  echo "  -s, --service   Specify the container"
  echo "  -b, --bash      Waiting for bash instead of starting app server"
  echo "  -d, --daemon    Start the container(s) in background"
  exit 0
fi

waitBash() {
  while [[ -z "$OUTPUT_KILL" ]]; do
    OUTPUT_KILL="$(docker-compose kill -s SIGUSR1 $ARG_SERVICE 2>&1)"
    sleep 1
  done
}

if [[ -n "$ARG_STARTBASH" ]]; then
  waitBash &
fi

docker-compose up $ARG_DAEMON $ARG_SERVICE

trap "kill $!" SIGINT
wait $!
