#!/usr/bin/env bash

while [[ $# > 0 ]]
do
  key="$1"
  case $key in
    -h|--help)
      ARG_HELP=YES
    ;;
    -c|--container)
      ARG_CONTAINER="$2"
      shift
    ;;
  esac
  shift
done

if [[ -n "$ARG_HELP" ]]; then
  echo "Stop the Docker containers"
  echo "  -c, --container   Specify the container"
  exit 0
fi

docker-compose stop $ARG_CONTAINER
