#!/usr/bin/env bash

while [[ $# > 0 ]]
do
  key="$1"
  case $key in
    -h|--help)
      ARG_HELP=YES
    ;;
    -s|--service)
      ARG_SERVICE="$2"
      shift
    ;;
  esac
  shift
done

if [[ -n "$ARG_HELP" ]]; then
  echo "Stop the Docker containers"
  echo "  -s, --service   Specify the container"
  exit 0
fi

docker-compose stop $ARG_SERVICE
